# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_state_blob.proto

require 'google/protobuf'

require 'proof_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("account_state_blob.proto", :syntax => :proto3) do
    add_message "types.AccountStateBlob" do
      optional :blob, :bytes, 1
    end
    add_message "types.AccountStateWithProof" do
      optional :version, :uint64, 1
      optional :blob, :message, 2, "types.AccountStateBlob"
      optional :proof, :message, 3, "types.AccountStateProof"
    end
  end
end

module Types
  AccountStateBlob = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.AccountStateBlob").msgclass
  AccountStateWithProof = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.AccountStateWithProof").msgclass
end
