# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: admission_control.proto for package 'admission_control'
# Original file comments:
# Copyright (c) The Libra Core Contributors
# SPDX-License-Identifier: Apache-2.0
#

require 'grpc'
require 'admission_control_pb'

module AdmissionControl
  module AdmissionControl
    # -----------------------------------------------------------------------------
    # ---------------- Service definition
    # -----------------------------------------------------------------------------
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'admission_control.AdmissionControl'

      # Public API to submit transaction to a validator.
      rpc :SubmitTransaction, SubmitTransactionRequest, SubmitTransactionResponse
      # This API is used to update the client to the latest ledger version and
      # optionally also request 1..n other pieces of data.  This allows for batch
      # queries.  All queries return proofs that a client should check to validate
      # the data. Note that if a client only wishes to update to the latest
      # LedgerInfo and receive the proof of this latest version, they can simply
      # omit the requested_items (or pass an empty list)
      rpc :UpdateToLatestLedger, Types::UpdateToLatestLedgerRequest, Types::UpdateToLatestLedgerResponse
    end

    Stub = Service.rpc_stub_class
  end
end
