# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admission_control.proto

require 'google/protobuf'

require 'get_with_proof_pb'
require 'transaction_pb'
require 'proof_pb'
require 'ledger_info_pb'
require 'vm_errors_pb'
require 'mempool_status_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("admission_control.proto", :syntax => :proto3) do
    add_message "admission_control.SubmitTransactionRequest" do
      optional :signed_txn, :message, 1, "types.SignedTransaction"
    end
    add_message "admission_control.SubmitTransactionResponse" do
      optional :validator_id, :bytes, 4
      oneof :status do
        optional :vm_status, :message, 1, "types.VMStatus"
        optional :ac_status, :enum, 2, "admission_control.AdmissionControlStatus"
        optional :mempool_status, :enum, 3, "mempool.MempoolAddTransactionStatus"
      end
    end
    add_enum "admission_control.AdmissionControlStatus" do
      value :Accepted, 0
      value :Blacklisted, 1
      value :Rejected, 2
    end
  end
end

module AdmissionControl
  SubmitTransactionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("admission_control.SubmitTransactionRequest").msgclass
  SubmitTransactionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("admission_control.SubmitTransactionResponse").msgclass
  AdmissionControlStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("admission_control.AdmissionControlStatus").enummodule
end
