# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto

require 'google/protobuf'

require 'access_path_pb'
require 'proof_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("events.proto", :syntax => :proto3) do
    add_message "types.Event" do
      optional :key, :bytes, 1
      optional :sequence_number, :uint64, 2
      optional :event_data, :bytes, 3
    end
    add_message "types.EventWithProof" do
      optional :transaction_version, :uint64, 1
      optional :event_index, :uint64, 2
      optional :event, :message, 3, "types.Event"
      optional :proof, :message, 4, "types.EventProof"
    end
    add_message "types.EventsList" do
      repeated :events, :message, 1, "types.Event"
    end
    add_message "types.EventsForVersions" do
      repeated :events_for_version, :message, 1, "types.EventsList"
    end
  end
end

module Types
  Event = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.Event").msgclass
  EventWithProof = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.EventWithProof").msgclass
  EventsList = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.EventsList").msgclass
  EventsForVersions = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.EventsForVersions").msgclass
end
