# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: execution.proto for package 'execution'
# Original file comments:
# Copyright (c) The Libra Core Contributors
# SPDX-License-Identifier: Apache-2.0
#

require 'grpc'
require 'execution_pb'

module Execution
  module Execution
    # -----------------------------------------------------------------------------
    # ---------------- Execution Service Definition
    # -----------------------------------------------------------------------------
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'execution.Execution'

      # Execute a list of signed transactions given by consensus. Return the id
      # of the block and the root hash of the ledger after applying transactions
      # in this block.
      rpc :ExecuteBlock, ExecuteBlockRequest, ExecuteBlockResponse
      # Commit a previously executed block that has been agreed by consensus.
      rpc :CommitBlock, CommitBlockRequest, CommitBlockResponse
      # Execute and commit a list of signed transactions received from peer
      # during synchronization. Return the id of the block
      rpc :ExecuteChunk, ExecuteChunkRequest, ExecuteChunkResponse
    end

    Stub = Service.rpc_stub_class
  end
end
