# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: execution.proto

require 'google/protobuf'

require 'get_with_proof_pb'
require 'ledger_info_pb'
require 'transaction_pb'
require 'validator_set_pb'
require 'vm_errors_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("execution.proto", :syntax => :proto3) do
    add_message "execution.ExecuteBlockRequest" do
      repeated :transactions, :message, 1, "types.SignedTransaction"
      optional :parent_block_id, :bytes, 2
      optional :block_id, :bytes, 3
    end
    add_message "execution.ExecuteBlockResponse" do
      optional :root_hash, :bytes, 1
      repeated :status, :message, 2, "types.VMStatus"
      optional :version, :uint64, 3
      optional :validators, :message, 4, "types.ValidatorSet"
    end
    add_message "execution.CommitBlockRequest" do
      optional :ledger_info_with_sigs, :message, 1, "types.LedgerInfoWithSignatures"
    end
    add_message "execution.CommitBlockResponse" do
      optional :status, :enum, 1, "execution.CommitBlockStatus"
    end
    add_message "execution.ExecuteChunkRequest" do
      optional :txn_list_with_proof, :message, 1, "types.TransactionListWithProof"
      optional :ledger_info_with_sigs, :message, 2, "types.LedgerInfoWithSignatures"
    end
    add_message "execution.ExecuteChunkResponse" do
    end
    add_enum "execution.CommitBlockStatus" do
      value :SUCCEEDED, 0
      value :FAILED, 1
    end
  end
end

module Execution
  ExecuteBlockRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("execution.ExecuteBlockRequest").msgclass
  ExecuteBlockResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("execution.ExecuteBlockResponse").msgclass
  CommitBlockRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("execution.CommitBlockRequest").msgclass
  CommitBlockResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("execution.CommitBlockResponse").msgclass
  ExecuteChunkRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("execution.ExecuteChunkRequest").msgclass
  ExecuteChunkResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("execution.ExecuteChunkResponse").msgclass
  CommitBlockStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("execution.CommitBlockStatus").enummodule
end
