# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: get_with_proof.proto

require 'google/protobuf'

require 'access_path_pb'
require 'account_state_blob_pb'
require 'events_pb'
require 'ledger_info_pb'
require 'transaction_pb'
require 'validator_change_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("get_with_proof.proto", :syntax => :proto3) do
    add_message "types.UpdateToLatestLedgerRequest" do
      optional :client_known_version, :uint64, 1
      repeated :requested_items, :message, 2, "types.RequestItem"
    end
    add_message "types.RequestItem" do
      oneof :requested_items do
        optional :get_account_state_request, :message, 1, "types.GetAccountStateRequest"
        optional :get_account_transaction_by_sequence_number_request, :message, 2, "types.GetAccountTransactionBySequenceNumberRequest"
        optional :get_events_by_event_access_path_request, :message, 3, "types.GetEventsByEventAccessPathRequest"
        optional :get_transactions_request, :message, 4, "types.GetTransactionsRequest"
      end
    end
    add_message "types.UpdateToLatestLedgerResponse" do
      repeated :response_items, :message, 1, "types.ResponseItem"
      optional :ledger_info_with_sigs, :message, 2, "types.LedgerInfoWithSignatures"
      repeated :validator_change_events, :message, 3, "types.ValidatorChangeEventWithProof"
    end
    add_message "types.ResponseItem" do
      oneof :response_items do
        optional :get_account_state_response, :message, 3, "types.GetAccountStateResponse"
        optional :get_account_transaction_by_sequence_number_response, :message, 4, "types.GetAccountTransactionBySequenceNumberResponse"
        optional :get_events_by_event_access_path_response, :message, 5, "types.GetEventsByEventAccessPathResponse"
        optional :get_transactions_response, :message, 6, "types.GetTransactionsResponse"
      end
    end
    add_message "types.GetAccountStateRequest" do
      optional :address, :bytes, 1
    end
    add_message "types.GetAccountStateResponse" do
      optional :account_state_with_proof, :message, 1, "types.AccountStateWithProof"
    end
    add_message "types.GetAccountTransactionBySequenceNumberRequest" do
      optional :account, :bytes, 1
      optional :sequence_number, :uint64, 2
      optional :fetch_events, :bool, 3
    end
    add_message "types.GetAccountTransactionBySequenceNumberResponse" do
      optional :signed_transaction_with_proof, :message, 2, "types.SignedTransactionWithProof"
      optional :proof_of_current_sequence_number, :message, 3, "types.AccountStateWithProof"
    end
    add_message "types.GetEventsByEventAccessPathRequest" do
      optional :access_path, :message, 1, "types.AccessPath"
      optional :start_event_seq_num, :uint64, 2
      optional :ascending, :bool, 3
      optional :limit, :uint64, 4
    end
    add_message "types.GetEventsByEventAccessPathResponse" do
      repeated :events_with_proof, :message, 1, "types.EventWithProof"
      optional :proof_of_latest_event, :message, 2, "types.AccountStateWithProof"
    end
    add_message "types.GetTransactionsRequest" do
      optional :start_version, :uint64, 1
      optional :limit, :uint64, 2
      optional :fetch_events, :bool, 3
    end
    add_message "types.GetTransactionsResponse" do
      optional :txn_list_with_proof, :message, 1, "types.TransactionListWithProof"
    end
  end
end

module Types
  UpdateToLatestLedgerRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.UpdateToLatestLedgerRequest").msgclass
  RequestItem = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.RequestItem").msgclass
  UpdateToLatestLedgerResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.UpdateToLatestLedgerResponse").msgclass
  ResponseItem = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ResponseItem").msgclass
  GetAccountStateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.GetAccountStateRequest").msgclass
  GetAccountStateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.GetAccountStateResponse").msgclass
  GetAccountTransactionBySequenceNumberRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.GetAccountTransactionBySequenceNumberRequest").msgclass
  GetAccountTransactionBySequenceNumberResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.GetAccountTransactionBySequenceNumberResponse").msgclass
  GetEventsByEventAccessPathRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.GetEventsByEventAccessPathRequest").msgclass
  GetEventsByEventAccessPathResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.GetEventsByEventAccessPathResponse").msgclass
  GetTransactionsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.GetTransactionsRequest").msgclass
  GetTransactionsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.GetTransactionsResponse").msgclass
end
