# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: language_storage.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("language_storage.proto", :syntax => :proto3) do
    add_message "types.ModuleId" do
      optional :address, :bytes, 1
      optional :name, :string, 2
    end
  end
end

module Types
  ModuleId = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ModuleId").msgclass
end
