# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ledger_info.proto

require 'google/protobuf'

require 'validator_set_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("ledger_info.proto", :syntax => :proto3) do
    add_message "types.LedgerInfo" do
      optional :version, :uint64, 1
      optional :transaction_accumulator_hash, :bytes, 2
      optional :consensus_data_hash, :bytes, 3
      optional :consensus_block_id, :bytes, 4
      optional :epoch_num, :uint64, 5
      optional :timestamp_usecs, :uint64, 6
      optional :next_validator_set, :message, 7, "types.ValidatorSet"
    end
    add_message "types.LedgerInfoWithSignatures" do
      repeated :signatures, :message, 1, "types.ValidatorSignature"
      optional :ledger_info, :message, 2, "types.LedgerInfo"
    end
    add_message "types.ValidatorSignature" do
      optional :validator_id, :bytes, 1
      optional :signature, :bytes, 2
    end
  end
end

module Types
  LedgerInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.LedgerInfo").msgclass
  LedgerInfoWithSignatures = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.LedgerInfoWithSignatures").msgclass
  ValidatorSignature = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ValidatorSignature").msgclass
end
