# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mempool_status.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("mempool_status.proto", :syntax => :proto3) do
    add_enum "mempool.MempoolAddTransactionStatus" do
      value :Valid, 0
      value :InsufficientBalance, 1
      value :InvalidSeqNumber, 2
      value :MempoolIsFull, 3
      value :TooManyTransactions, 4
      value :InvalidUpdate, 5
    end
  end
end

module Mempool
  MempoolAddTransactionStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("mempool.MempoolAddTransactionStatus").enummodule
end
