# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("network.proto", :syntax => :proto3) do
    add_message "network.PeerInfo" do
      optional :epoch, :uint64, 1
      repeated :addrs, :bytes, 2
    end
    add_message "network.SignedPeerInfo" do
      optional :peer_info, :bytes, 1
      optional :signature, :bytes, 2
    end
    add_message "network.FullNodePayload" do
      optional :epoch, :uint64, 1
      optional :dns_seed_addr, :bytes, 2
    end
    add_message "network.SignedFullNodePayload" do
      optional :payload, :bytes, 1
      optional :signature, :bytes, 2
    end
    add_message "network.Note" do
      optional :peer_id, :bytes, 1
      optional :signed_peer_info, :message, 2, "network.SignedPeerInfo"
      optional :signed_full_node_payload, :message, 3, "network.SignedFullNodePayload"
    end
    add_message "network.DiscoveryMsg" do
      repeated :notes, :message, 1, "network.Note"
    end
    add_message "network.IdentityMsg" do
      optional :peer_id, :bytes, 1
      repeated :supported_protocols, :bytes, 2
      optional :role, :enum, 3, "network.IdentityMsg.Role"
    end
    add_enum "network.IdentityMsg.Role" do
      value :VALIDATOR, 0
      value :FULL_NODE, 1
    end
    add_message "network.Ping" do
    end
    add_message "network.Pong" do
    end
  end
end

module Network
  PeerInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("network.PeerInfo").msgclass
  SignedPeerInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("network.SignedPeerInfo").msgclass
  FullNodePayload = Google::Protobuf::DescriptorPool.generated_pool.lookup("network.FullNodePayload").msgclass
  SignedFullNodePayload = Google::Protobuf::DescriptorPool.generated_pool.lookup("network.SignedFullNodePayload").msgclass
  Note = Google::Protobuf::DescriptorPool.generated_pool.lookup("network.Note").msgclass
  DiscoveryMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("network.DiscoveryMsg").msgclass
  IdentityMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("network.IdentityMsg").msgclass
  IdentityMsg::Role = Google::Protobuf::DescriptorPool.generated_pool.lookup("network.IdentityMsg.Role").enummodule
  Ping = Google::Protobuf::DescriptorPool.generated_pool.lookup("network.Ping").msgclass
  Pong = Google::Protobuf::DescriptorPool.generated_pool.lookup("network.Pong").msgclass
end
