# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: node_debug_interface.proto for package 'debug'
# Original file comments:
# Copyright (c) The Libra Core Contributors
# SPDX-License-Identifier: Apache-2.0
#
# A Debugging interface to be used to query debug information from a Node

require 'grpc'
require 'node_debug_interface_pb'

module Debug
  module NodeDebugInterface
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'debug.NodeDebugInterface'

      # Returns debug information about node
      rpc :GetNodeDetails, GetNodeDetailsRequest, GetNodeDetailsResponse
      # Returns recent events generated by event! macro
      rpc :GetEvents, GetEventsRequest, GetEventsResponse
      # Triggers a dump of heap profile.
      rpc :DumpJemallocHeapProfile, DumpJemallocHeapProfileRequest, DumpJemallocHeapProfileResponse
    end

    Stub = Service.rpc_stub_class
  end
end
