# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: node_debug_interface.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("node_debug_interface.proto", :syntax => :proto3) do
    add_message "debug.GetNodeDetailsRequest" do
    end
    add_message "debug.GetNodeDetailsResponse" do
      map :stats, :string, :string, 1
    end
    add_message "debug.GetEventsRequest" do
    end
    add_message "debug.GetEventsResponse" do
      repeated :events, :message, 1, "debug.Event"
    end
    add_message "debug.Event" do
      optional :name, :string, 1
      optional :timestamp, :int64, 2
      optional :json, :string, 3
    end
  end
end

module Debug
  GetNodeDetailsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("debug.GetNodeDetailsRequest").msgclass
  GetNodeDetailsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("debug.GetNodeDetailsResponse").msgclass
  GetEventsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("debug.GetEventsRequest").msgclass
  GetEventsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("debug.GetEventsResponse").msgclass
  Event = Google::Protobuf::DescriptorPool.generated_pool.lookup("debug.Event").msgclass
end
