# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: secret_service.proto for package 'secret_service'
# Original file comments:
# Copyright (c) The Libra Core Contributors
# SPDX-License-Identifier: Apache-2.0
#

require 'grpc'
require 'secret_service_pb'

module SecretService
  module SecretService
    # -----------------------------------------------------------------------------
    # ---------------- Service definition
    # -----------------------------------------------------------------------------
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'secret_service.SecretService'

      # API to request key generation
      rpc :GenerateKey, GenerateKeyRequest, GenerateKeyResponse
      # API to request a public key
      rpc :GetPublicKey, PublicKeyRequest, PublicKeyResponse
      # API to request a signature
      rpc :Sign, SignRequest, SignResponse
    end

    Stub = Service.rpc_stub_class
  end
end
