# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secret_service.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("secret_service.proto", :syntax => :proto3) do
    add_message "secret_service.GenerateKeyRequest" do
      optional :spec, :enum, 1, "secret_service.KeyType"
    end
    add_message "secret_service.GenerateKeyResponse" do
      optional :key_id, :bytes, 1
      optional :code, :enum, 2, "secret_service.ErrorCode"
    end
    add_message "secret_service.PublicKeyRequest" do
      optional :key_id, :bytes, 1
    end
    add_message "secret_service.PublicKeyResponse" do
      optional :public_key, :bytes, 1
      optional :code, :enum, 2, "secret_service.ErrorCode"
    end
    add_message "secret_service.SignRequest" do
      optional :key_id, :bytes, 1
      optional :message_hash, :bytes, 2
    end
    add_message "secret_service.SignResponse" do
      optional :signature, :bytes, 1
      optional :code, :enum, 2, "secret_service.ErrorCode"
    end
    add_enum "secret_service.ErrorCode" do
      value :Success, 0
      value :KeyIdNotFound, 1
      value :WrongLength, 2
      value :InvalidParameters, 3
      value :AuthenticationFailed, 4
      value :Unspecified, 5
    end
    add_enum "secret_service.KeyType" do
      value :Ed25519, 0
      value :BLS12381, 1
    end
  end
end

module SecretService
  GenerateKeyRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("secret_service.GenerateKeyRequest").msgclass
  GenerateKeyResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("secret_service.GenerateKeyResponse").msgclass
  PublicKeyRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("secret_service.PublicKeyRequest").msgclass
  PublicKeyResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("secret_service.PublicKeyResponse").msgclass
  SignRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("secret_service.SignRequest").msgclass
  SignResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("secret_service.SignResponse").msgclass
  ErrorCode = Google::Protobuf::DescriptorPool.generated_pool.lookup("secret_service.ErrorCode").enummodule
  KeyType = Google::Protobuf::DescriptorPool.generated_pool.lookup("secret_service.KeyType").enummodule
end
