# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: state_synchronizer.proto

require 'google/protobuf'

require 'ledger_info_pb'
require 'transaction_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("state_synchronizer.proto", :syntax => :proto3) do
    add_message "network.GetChunkRequest" do
      optional :known_version, :uint64, 1
      optional :limit, :uint64, 2
      optional :timeout, :uint64, 3
      optional :ledger_info_with_sigs, :message, 4, "types.LedgerInfoWithSignatures"
    end
    add_message "network.GetChunkResponse" do
      optional :ledger_info_with_sigs, :message, 1, "types.LedgerInfoWithSignatures"
      optional :txn_list_with_proof, :message, 2, "types.TransactionListWithProof"
    end
    add_message "network.StateSynchronizerMsg" do
      oneof :message do
        optional :chunk_request, :message, 1, "network.GetChunkRequest"
        optional :chunk_response, :message, 2, "network.GetChunkResponse"
      end
    end
  end
end

module Network
  GetChunkRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("network.GetChunkRequest").msgclass
  GetChunkResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("network.GetChunkResponse").msgclass
  StateSynchronizerMsg = Google::Protobuf::DescriptorPool.generated_pool.lookup("network.StateSynchronizerMsg").msgclass
end
