# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto

require 'google/protobuf'

require 'get_with_proof_pb'
require 'ledger_info_pb'
require 'transaction_pb'
require 'account_state_blob_pb'
require 'proof_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("storage.proto", :syntax => :proto3) do
    add_message "storage.SaveTransactionsRequest" do
      repeated :txns_to_commit, :message, 1, "types.TransactionToCommit"
      optional :first_version, :uint64, 2
      optional :ledger_info_with_signatures, :message, 3, "types.LedgerInfoWithSignatures"
    end
    add_message "storage.SaveTransactionsResponse" do
    end
    add_message "storage.GetTransactionsRequest" do
      optional :start_version, :uint64, 1
      optional :batch_size, :uint64, 2
      optional :ledger_version, :uint64, 3
      optional :fetch_events, :bool, 4
    end
    add_message "storage.GetTransactionsResponse" do
      optional :txn_list_with_proof, :message, 1, "types.TransactionListWithProof"
    end
    add_message "storage.GetAccountStateWithProofByVersionRequest" do
      optional :address, :bytes, 1
      optional :version, :uint64, 2
    end
    add_message "storage.GetAccountStateWithProofByVersionResponse" do
      optional :account_state_blob, :message, 1, "types.AccountStateBlob"
      optional :sparse_merkle_proof, :message, 2, "types.SparseMerkleProof"
    end
    add_message "storage.GetStartupInfoRequest" do
    end
    add_message "storage.GetStartupInfoResponse" do
      optional :info, :message, 1, "storage.StartupInfo"
    end
    add_message "storage.StartupInfo" do
      optional :ledger_info, :message, 1, "types.LedgerInfo"
      optional :latest_version, :uint64, 2
      optional :account_state_root_hash, :bytes, 3
      repeated :ledger_frozen_subtree_hashes, :bytes, 4
    end
  end
end

module Storage
  SaveTransactionsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("storage.SaveTransactionsRequest").msgclass
  SaveTransactionsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("storage.SaveTransactionsResponse").msgclass
  GetTransactionsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("storage.GetTransactionsRequest").msgclass
  GetTransactionsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("storage.GetTransactionsResponse").msgclass
  GetAccountStateWithProofByVersionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("storage.GetAccountStateWithProofByVersionRequest").msgclass
  GetAccountStateWithProofByVersionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("storage.GetAccountStateWithProofByVersionResponse").msgclass
  GetStartupInfoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("storage.GetStartupInfoRequest").msgclass
  GetStartupInfoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("storage.GetStartupInfoResponse").msgclass
  StartupInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("storage.StartupInfo").msgclass
end
