# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("test.proto", :syntax => :proto3) do
    add_message "test.Int32" do
      optional :value, :int32, 1
    end
    add_message "test.Int64" do
      optional :value, :int64, 1
    end
    add_message "test.UInt32" do
      optional :value, :uint32, 1
    end
    add_message "test.UInt64" do
      optional :value, :uint64, 1
    end
    add_message "test.SInt32" do
      optional :value, :sint32, 1
    end
    add_message "test.SInt64" do
      optional :value, :sint64, 1
    end
    add_message "test.Fixed32" do
      optional :value, :fixed32, 1
    end
    add_message "test.Fixed64" do
      optional :value, :fixed64, 1
    end
    add_message "test.Boolean" do
      optional :value, :bool, 1
    end
    add_message "test.Strings" do
      optional :value, :string, 1
    end
    add_message "test.Bytes" do
      optional :value, :bytes, 1
    end
    add_message "test.Repeated" do
      repeated :value, :message, 1, "test.Int32"
    end
    add_message "test.Structs" do
      optional :a, :message, 1, "test.Int32"
      optional :b, :message, 2, "test.UInt32"
      optional :c, :message, 3, "test.SInt32"
      optional :d, :message, 4, "test.Fixed32"
      optional :e, :message, 5, "test.Boolean"
      optional :f, :message, 6, "test.Strings"
      optional :g, :message, 7, "test.Bytes"
      repeated :h, :message, 8, "test.Int32"
    end
  end
end

module Test
  Int32 = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.Int32").msgclass
  Int64 = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.Int64").msgclass
  UInt32 = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.UInt32").msgclass
  UInt64 = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.UInt64").msgclass
  SInt32 = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.SInt32").msgclass
  SInt64 = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.SInt64").msgclass
  Fixed32 = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.Fixed32").msgclass
  Fixed64 = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.Fixed64").msgclass
  Boolean = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.Boolean").msgclass
  Strings = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.Strings").msgclass
  Bytes = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.Bytes").msgclass
  Repeated = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.Repeated").msgclass
  Structs = Google::Protobuf::DescriptorPool.generated_pool.lookup("test.Structs").msgclass
end
