# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction_info.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("transaction_info.proto", :syntax => :proto3) do
    add_message "types.TransactionInfo" do
      optional :signed_transaction_hash, :bytes, 1
      optional :state_root_hash, :bytes, 2
      optional :event_root_hash, :bytes, 3
      optional :gas_used, :uint64, 4
    end
  end
end

module Types
  TransactionInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.TransactionInfo").msgclass
end
