# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

require 'google/protobuf'

require 'access_path_pb'
require 'events_pb'
require 'proof_pb'
require 'transaction_info_pb'
require 'google/protobuf/wrappers_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("transaction.proto", :syntax => :proto3) do
    add_message "types.TransactionArgument" do
    end
    add_enum "types.TransactionArgument.ArgType" do
      value :U64, 0
      value :ADDRESS, 1
      value :STRING, 2
      value :BYTEARRAY, 3
    end
    add_message "types.SignedTransaction" do
      optional :signed_txn, :bytes, 5
    end
    add_message "types.SignedTransactionWithProof" do
      optional :version, :uint64, 1
      optional :signed_transaction, :message, 2, "types.SignedTransaction"
      optional :proof, :message, 3, "types.SignedTransactionProof"
      optional :events, :message, 4, "types.EventsList"
    end
    add_message "types.SignedTransactionsBlock" do
      repeated :transactions, :message, 1, "types.SignedTransaction"
      optional :validator_public_key, :bytes, 2
      optional :validator_signature, :bytes, 3
    end
    add_message "types.AccountState" do
      optional :address, :bytes, 1
      optional :blob, :bytes, 2
    end
    add_message "types.TransactionToCommit" do
      optional :signed_txn, :message, 1, "types.SignedTransaction"
      repeated :account_states, :message, 2, "types.AccountState"
      repeated :events, :message, 3, "types.Event"
      optional :gas_used, :uint64, 4
    end
    add_message "types.TransactionListWithProof" do
      repeated :transactions, :message, 1, "types.SignedTransaction"
      repeated :infos, :message, 2, "types.TransactionInfo"
      optional :events_for_versions, :message, 3, "types.EventsForVersions"
      optional :first_transaction_version, :message, 4, "google.protobuf.UInt64Value"
      optional :proof_of_first_transaction, :message, 5, "types.AccumulatorProof"
      optional :proof_of_last_transaction, :message, 6, "types.AccumulatorProof"
    end
  end
end

module Types
  TransactionArgument = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.TransactionArgument").msgclass
  TransactionArgument::ArgType = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.TransactionArgument.ArgType").enummodule
  SignedTransaction = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.SignedTransaction").msgclass
  SignedTransactionWithProof = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.SignedTransactionWithProof").msgclass
  SignedTransactionsBlock = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.SignedTransactionsBlock").msgclass
  AccountState = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.AccountState").msgclass
  TransactionToCommit = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.TransactionToCommit").msgclass
  TransactionListWithProof = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.TransactionListWithProof").msgclass
end
