# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: validator_change.proto

require 'google/protobuf'

require 'events_pb'
require 'ledger_info_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("validator_change.proto", :syntax => :proto3) do
    add_message "types.ValidatorChangeEventWithProof" do
      optional :ledger_info_with_sigs, :message, 1, "types.LedgerInfoWithSignatures"
      optional :event_with_proof, :message, 2, "types.EventWithProof"
    end
  end
end

module Types
  ValidatorChangeEventWithProof = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ValidatorChangeEventWithProof").msgclass
end
