# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: validator_set.proto

require 'google/protobuf'

require 'validator_public_keys_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("validator_set.proto", :syntax => :proto3) do
    add_message "types.ValidatorSet" do
      repeated :validator_public_keys, :message, 1, "types.ValidatorPublicKeys"
    end
  end
end

module Types
  ValidatorSet = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ValidatorSet").msgclass
end
