# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm_errors.proto

require 'google/protobuf'

require 'language_storage_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vm_errors.proto", :syntax => :proto3) do
    add_message "types.VMStatus" do
      optional :major_status, :uint64, 1
      optional :has_sub_status, :bool, 2
      optional :sub_status, :uint64, 3
      optional :has_message, :bool, 4
      optional :message, :string, 5
    end
  end
end

module Types
  VMStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.VMStatus").msgclass
end
