# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm_errors.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vm_errors.proto", :syntax => :proto3) do
    add_message "types.VMValidationStatus" do
      optional :code, :enum, 1, "types.VMValidationStatusCode"
      optional :message, :string, 2
    end
    add_message "types.VMVerificationStatusList" do
      repeated :status_list, :message, 1, "types.VMVerificationStatus"
    end
    add_message "types.VMVerificationStatus" do
      optional :status_kind, :enum, 1, "types.VMVerificationStatus.StatusKind"
      optional :module_idx, :uint32, 2
      optional :error_kind, :enum, 3, "types.VMVerificationErrorKind"
      optional :message, :string, 4
    end
    add_enum "types.VMVerificationStatus.StatusKind" do
      value :SCRIPT, 0
      value :MODULE, 1
    end
    add_message "types.AssertionFailure" do
      optional :assertion_error_code, :uint64, 1
    end
    add_message "types.ArithmeticError" do
      optional :error_code, :enum, 1, "types.ArithmeticError.ArithmeticErrorType"
    end
    add_enum "types.ArithmeticError.ArithmeticErrorType" do
      value :UnknownArithmeticError, 0
      value :Underflow, 1
      value :Overflow, 2
      value :DivisionByZero, 3
    end
    add_message "types.DynamicReferenceError" do
      optional :error_code, :enum, 1, "types.DynamicReferenceError.DynamicReferenceErrorType"
    end
    add_enum "types.DynamicReferenceError.DynamicReferenceErrorType" do
      value :UnknownDynamicReferenceError, 0
      value :MoveOfBorrowedResource, 1
      value :GlobalRefAlreadyReleased, 2
      value :MissingReleaseRef, 3
      value :GlobalAlreadyBorrowed, 4
    end
    add_message "types.ExecutionStatus" do
      oneof :execution_status do
        optional :runtime_status, :enum, 1, "types.RuntimeStatus"
        optional :assertion_failure, :message, 2, "types.AssertionFailure"
        optional :arithmetic_error, :message, 3, "types.ArithmeticError"
        optional :reference_error, :message, 4, "types.DynamicReferenceError"
      end
    end
    add_message "types.VMStatus" do
      oneof :error_type do
        optional :validation, :message, 1, "types.VMValidationStatus"
        optional :verification, :message, 2, "types.VMVerificationStatusList"
        optional :invariant_violation, :enum, 3, "types.VMInvariantViolationError"
        optional :deserialization, :enum, 4, "types.BinaryError"
        optional :execution, :message, 5, "types.ExecutionStatus"
      end
    end
    add_enum "types.VMValidationStatusCode" do
      value :UnknownValidationStatus, 0
      value :InvalidSignature, 1
      value :InvalidAuthKey, 2
      value :SequenceNumberTooOld, 3
      value :SequenceNumberTooNew, 4
      value :InsufficientBalanceForTransactionFee, 5
      value :TransactionExpired, 6
      value :SendingAccountDoesNotExist, 7
      value :RejectedWriteSet, 8
      value :InvalidWriteSet, 9
      value :ExceededMaxTransactionSize, 10
      value :UnknownScript, 11
      value :UnknownModule, 12
      value :MaxGasUnitsExceedsMaxGasUnitsBound, 13
      value :MaxGasUnitsBelowMinTransactionGasUnits, 14
      value :GasUnitPriceBelowMinBound, 15
      value :GasUnitPriceAboveMaxBound, 16
    end
    add_enum "types.VMVerificationErrorKind" do
      value :UnknownVerificationError, 0
      value :IndexOutOfBounds, 1
      value :RangeOutOfBounds, 2
      value :InvalidSignatureToken, 3
      value :InvalidFieldDefReference, 4
      value :RecursiveStructDefinition, 5
      value :InvalidResourceField, 6
      value :InvalidFallThrough, 7
      value :JoinFailure, 8
      value :NegativeStackSizeWithinBlock, 9
      value :UnbalancedStack, 10
      value :InvalidMainFunctionSignature, 11
      value :DuplicateElement, 12
      value :InvalidModuleHandle, 13
      value :UnimplementedHandle, 14
      value :InconsistentFields, 15
      value :UnusedFields, 16
      value :LookupFailed, 17
      value :VisibilityMismatch, 18
      value :TypeResolutionFailure, 19
      value :TypeMismatch, 20
      value :MissingDependency, 21
      value :PopReferenceError, 22
      value :PopResourceError, 23
      value :ReleaseRefTypeMismatchError, 24
      value :BrTypeMismatchError, 25
      value :AssertTypeMismatchError, 26
      value :StLocTypeMismatchError, 27
      value :StLocUnsafeToDestroyError, 28
      value :RetUnsafeToDestroyError, 29
      value :RetTypeMismatchError, 30
      value :FreezeRefTypeMismatchError, 31
      value :FreezeRefExistsMutableBorrowError, 32
      value :BorrowFieldTypeMismatchError, 33
      value :BorrowFieldBadFieldError, 34
      value :BorrowFieldExistsMutableBorrowError, 35
      value :CopyLocUnavailableError, 36
      value :CopyLocResourceError, 37
      value :CopyLocExistsBorrowError, 38
      value :MoveLocUnavailableError, 39
      value :MoveLocExistsBorrowError, 40
      value :BorrowLocReferenceError, 41
      value :BorrowLocUnavailableError, 42
      value :BorrowLocExistsBorrowError, 43
      value :CallTypeMismatchError, 44
      value :CallBorrowedMutableReferenceError, 45
      value :PackTypeMismatchError, 46
      value :UnpackTypeMismatchError, 47
      value :ReadRefTypeMismatchError, 48
      value :ReadRefResourceError, 49
      value :ReadRefExistsMutableBorrowError, 50
      value :WriteRefTypeMismatchError, 51
      value :WriteRefResourceError, 52
      value :WriteRefExistsBorrowError, 53
      value :WriteRefNoMutableReferenceError, 54
      value :IntegerOpTypeMismatchError, 55
      value :BooleanOpTypeMismatchError, 56
      value :EqualityOpTypeMismatchError, 57
      value :ExistsResourceTypeMismatchError, 58
      value :BorrowGlobalTypeMismatchError, 59
      value :BorrowGlobalNoResourceError, 60
      value :MoveFromTypeMismatchError, 61
      value :MoveFromNoResourceError, 62
      value :MoveToSenderTypeMismatchError, 63
      value :MoveToSenderNoResourceError, 64
      value :CreateAccountTypeMismatchError, 65
      value :ModuleAddressDoesNotMatchSender, 66
      value :NoModuleHandles, 67
    end
    add_enum "types.VMInvariantViolationError" do
      value :UnknownInvariantViolationError, 0
      value :OutOfBoundsIndex, 1
      value :OutOfBoundsRange, 2
      value :EmptyValueStack, 3
      value :EmptyCallStack, 4
      value :PCOverflow, 5
      value :LinkerError, 6
      value :LocalReferenceError, 7
      value :StorageError, 8
    end
    add_enum "types.BinaryError" do
      value :UnknownBinaryError, 0
      value :Malformed, 1
      value :BadMagic, 2
      value :UnknownVersion, 3
      value :UnknownTableType, 4
      value :UnknownSignatureType, 5
      value :UnknownSerializedType, 6
      value :UnknownOpcode, 7
      value :BadHeaderTable, 8
      value :UnexpectedSignatureType, 9
      value :DuplicateTable, 10
    end
    add_enum "types.RuntimeStatus" do
      value :UnknownRuntimeStatus, 0
      value :Executed, 1
      value :OutOfGas, 2
      value :ResourceDoesNotExist, 3
      value :ResourceAlreadyExists, 4
      value :EvictedAccountAccess, 5
      value :AccountAddressAlreadyExists, 6
      value :TypeError, 7
      value :MissingData, 8
      value :DataFormatError, 9
      value :InvalidData, 10
      value :RemoteDataError, 11
      value :CannotWriteExistingResource, 12
      value :ValueSerializationError, 13
      value :ValueDeserializationError, 14
      value :DuplicateModuleName, 15
    end
  end
end

module Types
  VMValidationStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.VMValidationStatus").msgclass
  VMVerificationStatusList = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.VMVerificationStatusList").msgclass
  VMVerificationStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.VMVerificationStatus").msgclass
  VMVerificationStatus::StatusKind = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.VMVerificationStatus.StatusKind").enummodule
  AssertionFailure = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.AssertionFailure").msgclass
  ArithmeticError = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ArithmeticError").msgclass
  ArithmeticError::ArithmeticErrorType = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ArithmeticError.ArithmeticErrorType").enummodule
  DynamicReferenceError = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.DynamicReferenceError").msgclass
  DynamicReferenceError::DynamicReferenceErrorType = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.DynamicReferenceError.DynamicReferenceErrorType").enummodule
  ExecutionStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.ExecutionStatus").msgclass
  VMStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.VMStatus").msgclass
  VMValidationStatusCode = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.VMValidationStatusCode").enummodule
  VMVerificationErrorKind = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.VMVerificationErrorKind").enummodule
  VMInvariantViolationError = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.VMInvariantViolationError").enummodule
  BinaryError = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.BinaryError").enummodule
  RuntimeStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("types.RuntimeStatus").enummodule
end
